version: '3'

services:
  web:
    build: ./web-service
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  worker:
    build: ./worker-service
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
